### ISSUE TITLE
倉庫如何使用

### ISSUE THREAD

**Issue by superfpga** [ryan4yin/nix-config#111]
朋友您好，最近對你的book和倉庫進行了閱讀和使用，受益匪淺，但是有些問題，請教一下：

1. 我將你的倉庫download下來，直接放在了/etc/nixos下
2. 執行nix flake update或者sudo nixos-rebuild switch --flake .均會報如下錯誤
...................
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
warning: could not read HEAD ref from repo at 'ssh://git@github.com/ryan4yin/nix-secrets.git', using 'master'

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error:
       … while updating the lock file of flake 'path:/etc/nixos?lastModified=1711889533&narHash=sha256-RO3rlYZimWKQEgRdL9kCU0vbJdU5SWi8I7kHFmctKM4%3D'

       … while updating the flake input 'mysecrets'

       … while fetching the input 'git+ssh://git@github.com/ryan4yin/nix-secrets.git?shallow=1'

       error: program 'git' failed with exit code 128

3. 所以特此請教一下，我是否需要做一些配置上的修改，先謝謝了，忘指導一下
4. 微信：superfpgaer

**Comment by ryan4yin** [comment]
Same as #69，请先阅读一遍此仓库的 README，其中明确说明了这只是我的个人配置，不应该也不能够直接在你的个人机器上部署。
另外我并没有时间做私下的指导，我的文档已经将新人入门的难度降低许多了，建议自学或者加 NixOS 中文群交流。
如果阅读文档遇到问题，可以在 GitHub 提 Issue.

**Comment by superfpga** [comment]
謝謝 @ryan4yin
