### ISSUE TITLE
[Bug] the latest version of atuin in nixpkgs has problem to work with the latest version of nushell

### ISSUE THREAD

**Issue by DataEraserC** [ryan4yin/nix-config#119]
### Bug
The latest version of Atuin in nixpkgs is not working properly with the latest version of Nushell.

## Problem Details
The `atuin` tool faces issues when used in the latest version of Nushell. Refer to the issue raised at the Atuin repository for more information: [atuinsh/atuin#1934](https://github.com/atuinsh/atuin/issues/1934).

## Possible Solutions
1. Temporarily disable `atuin.enableNushellIntegration`.
2. Try substituting the value of `programs.atuin.package` with a different nix flake that offers an updated version of Atuin.
3. Consider downgrading the Nushell version.

**Comment by ryan4yin** [comment]
Thanks for the issue, I have just disabled `atuin.enableNushellIntegration` to avoid issues.

**Comment by DataEraserC** [comment]
@ryan4yin I have re-enabled atuin.enableNushellIntegration on my computer, and it seems to be working fine now.
