### ISSUE TITLE
在引入 clang-unwrapped 情况下，go运行错误

### ISSUE THREAD

**Issue by shelken** [ryan4yin/nix-config#122]
- 本项目
https://github.com/ryan4yin/nix-config/blob/21d85d41efed3bd6f1640efdf6f6d6f8ae5d8af2/home/base/tui/editors/packages.nix#L18

- 我的配置
https://github.com/shelken/nix-config/blob/c6269a6919fc378ed4854fa72b4da1b2ddbbf0b8/home/apps/neovim/packages.nix#L7

虽然我跟您的配置不完全一致，但是在只引入该包的情况下，在我的电脑上（darwin），直接运行 `go run .` 发现以下错误:

```log
# runtime/cgo
cgo-builtin-prolog:1:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 error generated
```

去掉就正常了。不知道你是否能复现？

**Comment by ryan4yin** [comment]
+1 成功复现...

**Comment by ryan4yin** [comment]
有可能是 unstable 的 clang 有不兼容变更，然后我 darwin 用的是  nixpkgs-23.11-darwin 不是 unstable 从而导致问题。

**Comment by imxyy1soope1** [comment]
大概是因为`llvmPackages.clang-unwrapped`找不到include path,可以换用`clang-tools`

**Comment by ryan4yin** [comment]
@imxyy1soope1 嗯应该是这样

**Comment by ryan4yin** [comment]
升级到 24.05 后问题仍旧存在，已经根据 @imxyy1soope1 的建议做了修改。
