### ISSUE TITLE
我看有加密的部分不知道能否在ESXi虚拟机中部署

### ISSUE THREAD

**Issue by llity** [ryan4yin/nix-config#138]
盘符加密部分是否可以删除。

谢谢分享配置，非常受用。

**Comment by ryan4yin** [comment]
虚拟机镜像可以用 nixos-generator 生成，它默认就不带加密。
我所有的 kubevirt 虚拟机都是用的这份 disk 配置，root on tmpfs 都没做，就用的 nixos-generator 默认分区：

https://github.com/ryan4yin/nix-config/blob/main/modules/nixos/server/kubevirt-hardware-configuration.nix

**Comment by llity** [comment]
感谢，需要大量的时间来部署。
