### ISSUE TITLE
rsync是否需要加上`--checksum`参数？

### ISSUE THREAD

**Issue by shelken** [ryan4yin/nix-config#142]
https://github.com/ryan4yin/nix-config/blob/3dc7ec1fe8033576a02ca15bdb05110a607d8619/utils.nu#L72

相同名字，且修改日期相同时（size不同）。发现rsync并没有正常传输。（可以尝试下，并用sha256sum检查），两边文件的sha256sum值不一样。
加入checksum参数后，两边重新sha256sum后，相同了

**Comment by ryan4yin** [comment]
Done https://github.com/ryan4yin/nix-config/commit/5a6ccd8794703c62e2de9d6d077c60336168778f
