### ISSUE TITLE
nvidia gpu support for nixpak firefox

### ISSUE THREAD

**Issue by sickle-phin** [ryan4yin/nix-config#165]
nixpak maybe needs this code.
`bubblewrap = {
        bind.ro = [
          "/etc/egl"
          "/etc/static/egl"
        ];
};
`
I always refer your awesome setup, thank you.

**Comment by sickle-phin** [comment]
And in addition to this...
` bind.dev = [
          "/dev/nvidia0"
          "/dev/nvidiactl"
          "/dev/nvidia-modeset"
          "/dev/nvidia-uvm"
        ];
`

**Comment by ryan4yin** [comment]
@sickle-phin problem solved! Thanks a lot! 3>
