### ISSUE TITLE
hyprland 在 home-manager 下的配置无法运行。

### ISSUE THREAD

**Issue by synebula** [ryan4yin/nix-config#17]
首先感谢大佬的NIX手册，跟着入了NIX的坑。
本来在arch上单独使用NIX，最近下定决心转向NIXOS，但是在hyprland配置上有些问题请教下大佬~

参考大佬的配置，发现 hyprland 也是配置在nixos下了，请问是否也是在 home-manager 下配置 hyprland 无法启动？
配置和大佬也是类似的 intel + nvidia 双GPU，同样配置在 nixos 下面正常启动，使用 home-manager 的配置就不行。

**Comment by ryan4yin** [comment]
是的，home-manager 下要配置启动，这个功能是最近几个月才有的，你可以把 nixpkgs 升级到 nixos-unstable，升级后或许就可行了。

**Comment by ryan4yin** [comment]
查看 home-manager 提交记录，在 2023/7/21 才刚加入了 hyprland 的支持：

https://github.com/nix-community/home-manager/commits/6a20e40acaebf067da682661aa67da8b36812606/modules/services/window-managers/hyprland.nix

**Comment by synebula** [comment]
谢谢帮助
