### ISSUE TITLE
关于 Steam 在 hyprland 启动

### ISSUE THREAD

**Issue by LokiSharp** [ryan4yin/nix-config#170]
我正在参考你的配置构建自己的系统，启动 Steam 提示 cannot connection to X。我发现你的 hyprland 配置里没有启用 xserver 和 xwayland。需要修改什么配置让 steam 支持在 hyprland 启动？

**Comment by ryan4yin** [comment]
很久没在 NixOS 上用过 Steam 了，你要不抄抄别人的配置吧，我估计是被我改坏掉了。

**Comment by DataEraserC** [comment]
我这边工作正常
另外hyprland的xwayland貌似是在这里启用了
https://mynixos.com/home-manager/option/wayland.windowManager.hyprland.xwayland.enable

**Comment by LokiSharp** [comment]
我知道原因了，我之前 pkgs 选择的 24.05 版本，切换到和你相同的 unstable 就没问题了。
