### ISSUE TITLE
！！！

### ISSUE THREAD

**Issue by zheshigewenti** [ryan4yin/nix-config#177]
你的博客中"用的是中文符号，对于初学nixos的我简直噩梦，强烈建议修改。

**Comment by ryan4yin** [comment]
如果你是指 NixOS & Flakes Book，我想你可以直接提个 PR。如果你是指我的博客，我博客里目前应该没有 NixOS 教程。

另外，请不要在我的 issue 区发泄情绪，正常地提 issue 我们可以讨论解决，带负面情绪的我直接忽略。

**Comment by ryan4yin** [comment]
> 有些唐突，有些抱歉

能互相理解是最好的，搞开源本来就是为爱发电，如果还要被个别读者指着鼻子骂「你哪里做得不对，浪费我多少时间！！！」，就太离谱了。

NixOS & Flakes Book 这本书，在英文世界我收到的是各种感谢跟真金白银，而在中文世界收到的确是这样的 issue，老实说我甚至有点对自己的国家感到失望。

有兴趣的话你可以看看各位英文读者给我留下的评论，再对比一下你这个 issue 最初的样子：

- https://github.com/ryan4yin/nixos-and-flakes-book/discussions/43
- https://buymeacoffee.com/ryan4yin

如果这些信息能让你认真思考一下开源是什么、使用开源项目遇到了问题时应该如何处理、是否可以在 issue 区发泄情绪恶心作者，就更好了。



> NixOS & Flakes Book上的一处"用了中文中的全角，致使写flake的时候导致不知名报错，只是想告诉一下作者

我不知道你指的是哪一处，但你可以试着提个 PR 修改一下，或者更具体点，引用一下相关段落，方便定位。

**Comment by zheshigewenti** [comment]
这是我个人的第一个issue，生活中直来直去习惯了，不必上升到群体层面，个人素质问题，再次道歉，感谢付出。

**Comment by Dream4ever** [comment]
> 这是我个人的第一个issue，生活中直来直去习惯了，不必上升到群体层面，是我个人素质问题，再次道歉，感谢付出。

有效的提问是把遇到的具体问题说出来，比如是哪里的中文全交导致了报错，报错信息是什么，这样别人才方便排查定位。

有效的提问也是一门学问，值得好好学习，可以参考一下著名大项目的 issue，在提交时都会有模板，来指引用户应当说明哪些信息。

**Comment by huwqchn** [comment]
> 这是我个人的第一个issue，生活中直来直去习惯了，不必上升到群体层面，是我个人素质问题，再次道歉，感谢付出。
> 
> 

虽然这么说，但是在GitHub上这样对开源作者指责式命令式的回复都是中国人，遇到多了难免失望https://github.com/zellij-org/zellij/issues/316#issuecomment-2106763538
