### ISSUE TITLE
请问一下这个name是在哪里获取的？

### ISSUE THREAD

**Issue by shelken** [ryan4yin/nix-config#18]
https://github.com/ryan4yin/nix-config/blob/6d2ba3f0c136bf76c7e8b230547c601030d7ba67/lib/colmenaSystem.nix#L13C26-L13C26

**Comment by ryan4yin** [comment]
这是 colmena 的指定格式，name 会在你执行 colmena 指令时由 colmena 传入，具体而言，它对应这里的 ruby/kana:

https://github.com/ryan4yin/nix-config/blob/6d2ba3f0c136bf76c7e8b230547c601030d7ba67/flake.nix#L205

**Comment by ryan4yin** [comment]
closed, 如果还有问题可以 reopen

**Comment by shelken** [comment]
明白了，谢谢\(^o^)/~
