### ISSUE TITLE
Need help in setting up VPN in nixOS

### ISSUE THREAD

**Issue by goodmorning-hwt** [ryan4yin/nix-config#29]
Hello,

I've read your tutorial on nixOS and it's great! I was wondering if you would be willing to share your config for VPN clients like clash and v2ray. I've been trying to set up a VPN on my nixOS machine for a while now but haven't found a good solution. I hope I can learn from your approach. 
It would be really helpful if you could share any solution or suggestions. Thank you in advance for your assistance.

**Comment by ryan4yin** [comment]
I'm using a bypass router(openwrt) to speed up my NixOS downloading, for some stuff like v2ray/dae, considering ask for help at https://t.me/nixos_zhcn

**Comment by ryan4yin** [comment]
FYI, how to setup http proxy for nix-daemon:
https://nixos-and-flakes.thiscute.world/nixos-with-flakes/add-custom-cache-servers#use-local-http-proxy-to-speed-up-nix-package-download

**Comment by goodmorning-hwt** [comment]
Thanks for your help! Let me have a try.

**Comment by goodmorning-hwt** [comment]
I solved my problem now. Thanks a lot!
