### ISSUE TITLE
[Bug]QQ:Cannot be launched normally at some situation(with possible solutions)

### ISSUE THREAD

**Issue by DataEraserC** [ryan4yin/nix-config#35]
### Describe the bug
QQ can not be launched
> I'm not quite sure if the problem is due to my improper operation.

### Steps To Reproduce
1. In Hyprland environment , launch QQ from anyrun/terminal

### Expected behavior
QQ can be launched normally

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.7-xanmod1, NixOS, 23.11 (Tapir), 23.11.20231218.d02ffbb`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(nixos): `"home-manager-23.05.tar.gz, nixpkgs"`
 - channels(root): `"nixos-23.05, nixos-hardware"`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`
```
---

### Possible solutions
use QQ from nixpkgs-unstable

**Comment by DataEraserC** [comment]
Possible related questions."
[Chromium issue in nixpkgs](https://github.com/NixOS/nixpkgs/issues/268490)
[Recent Commit in nixpkgs-unstable(qq)](https://github.com/NixOS/nixpkgs/commit/7e3940735af718435c7f34cbc1f0f9c0105e8159)

**Comment by ryan4yin** [comment]
@DataEraserC Thanks for reporting, haven't used QQ for a while.

**Comment by DataEraserC** [comment]
Hmm... After I changed it to nixpkgs-unstable, QQ can now be launched. However, it seems to crash for some strange reason. I'm not sure if it's due to some other settings on my device.
I think it's necessary to confirm with you whether everything is normal on your end.

**Comment by ryan4yin** [comment]
Basically I do not use QQ in wayland(Hyprland) 🤣 , it's buggy and painful.
I just tried it, it can be launched normally, but the font is jagged, and the chat window flashes and beats frequently.

**Comment by DataEraserC** [comment]
> Hmm... After I changed it to nixpkgs-unstable.qq, QQ can now be launched. However, it seems to crash for some strange reason. I'm not sure if it's due to some other settings on my device. I think it's necessary to confirm with you whether everything is normal on your end.

After testing the appimage version and using it, I didn't experience any crashes. Then, when I switched to the version from nixpkgs-unstable, it worked fine. It's really a strange issue.
