### ISSUE TITLE
希望增加flake版的clash meta功能

### ISSUE THREAD

**Issue by llity** [ryan4yin/nix-config#37]
感谢提供完善的nixos使用体验，希望增加flake版的clash meta功能，可以作为软路由使用。
[MetaCubeX/mihomo@Meta/flake.nix](https://github.com/MetaCubeX/mihomo/blob/Meta/flake.nix?rgh-link-date=2024-01-03T07%3A49%3A34Z) 的功能，谢谢

**Comment by ryan4yin** [comment]
这跟非 flake 版没啥区别啊，你可以直接参考这些配置：

Jason Wang: https://github.com/Guanran928/flake/blob/master/users/guanranwang/nixos/profiles/common/opt-in/clash-meta-client/default.nix

Yingchi Long: https://github.com/inclyc/flakes/blob/d1ad2fc7e01900baaf45261e58b9419d0c4b4b1a/nixos/modules/clash/default.nix

以及 clash-meta 自身文档：

https://wiki.metacubex.one/config/proxy-providers/

**Comment by ryan4yin** [comment]
哦你是想直接用它 flake 给出的 overlay 么？建议在 NixOS TG 群里问问吧，上面两个配置文件的作者都在群里：

https://t.me/nixos_zhcn

**Comment by llity** [comment]
这个clashmeta内核改名为mihomo，更新更及时，clash-meta 仓库版本更新较慢吧

**Comment by llity** [comment]
谢谢，我先看一下

**Comment by llity** [comment]
嗯，可以部署给虚拟机做软路由，之前用的openwrt，准备全部迁移到nixos上面。

**Comment by ryan4yin** [comment]
厉害了，我还是 openwrt 哈哈

**Comment by llity** [comment]
准备折腾以下你这套配置，桌面很好看。也是在学习，谢谢你的文档很全面。
