### ISSUE TITLE
nixos-installer swapfile

### ISSUE THREAD

**Issue by bananabr34d** [ryan4yin/nix-config#38]
Hi Ryan,

I've really enjoyed your book and reading your thorough notes in the config files.  When reviewing your nixos-installer I noticed that you are creating a 96g swapfile.  This seemed excessive to me and I was wondering what the rationale is.  I know you are using impermanence and loading into tmpfs, so perhaps its due to system compiling downloads?  

Also, sorry if this question isn't appropriate for github issues.  Feel free to close and delete if you don't want to answer.

**Comment by ryan4yin** [comment]
NixOS uses /tmp for compilation, and I have mount a btrfs subvolume to it, so it is sufficient.
This 96G swapfile is mainly used for loading some big LLM models. Some LLM models are often 30G or 80G in size, and I don't have enough memory.

It's true that such a big swapfile is not common.

**Comment by bananabr34d** [comment]
Thanks for the feedback and again, thanks so much for your NixOS book and this repository. You have greatly helped me on my Nix journey.
