### ISSUE TITLE
[Typo]

### ISSUE THREAD

**Issue by DataEraserC** [ryan4yin/nix-config#39]
[emacs-clear](https://github.com/ryan4yin/nix-config/blob/1d2bdc1bebd3893154b2a5850c57882e078e9169/home/base/desktop/editors/emacs/README.md?plain=1#L51)

[emacs-clean](https://github.com/ryan4yin/nix-config/blob/main/Justfile#L192)

**Comment by ryan4yin** [comment]
Thanks, fixed https://github.com/ryan4yin/nix-config/commit/9b96ff35d6044763f35f418e703705a9839d632d
