### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by oo-infty** [ryan4yin/nix-config#44]
`modules/nixos/base/visualisation.nix => modules/nixos/base/virtualization.nix`

**Comment by ryan4yin** [comment]
Thanks for the feedback, NixOS use `virtualisation`: <https://search.nixos.org/options?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=virtualisation>

Fixed by : https://github.com/ryan4yin/nix-config/commit/03d822da3fc02e264941198f27ca488899e436ba
