### ISSUE TITLE
Another ScreenShot Tool

### ISSUE THREAD

**Issue by DataEraserC** [ryan4yin/nix-config#55]
There is another screenshots tool for Hyprland (Only available on unstable channel): [pkgs-unstable.hyprshot](https://search.nixos.org/packages?channel=unstable&show=hyprshot&from=0&size=50&sort=relevance&type=packages&query=hyprshot)

I think we can give it a try. 

The command to try:
```shell
hyprshot -m window -o ~/Pictures/Screenshots -- imv
```

Hyprland keybind
```plaintext
# -- Screenshots --
bind=,Print,exec,hyprshot -m output -o ~/Pictures/Screenshots -- imv
bind=SUPER,Print,exec,hyprshot -m window -o ~/Pictures/Screenshots -- imv
bind=CTRL,Print,exec,hyprshot -m region -o ~/Pictures/Screenshots -- imv

```

**Comment by ryan4yin** [comment]
Thanks for recommending, I'll find time to try it.

**Comment by ryan4yin** [comment]
Just confirmed that the usage of hyprshot is the same as the screenshot script I used before, added!
https://github.com/ryan4yin/nix-config/commit/544ec79aff438ae5441d07b3bbcfece82738c098
