### ISSUE TITLE
[Bug] autin do not record some shell commands in its hitory

### ISSUE THREAD

**Issue by ryan4yin** [ryan4yin/nix-config#61]
Cases:

1. Any commands starts with spaces, such as ` ls`.
2. ...

It's weird.

**Comment by mifix** [comment]
Hey,

this could answer your question: https://github.com/atuinsh/atuin/commit/f55d5cf0bfa59af144788bec7c9d0a9ada71aad4

(zsh has an option HIST_IGNORE_SPACE too)

Thank you for your nix config! Helped me a lot.

**Comment by ryan4yin** [comment]
@mifix Thanks for the info, so it's already a feature request related to this: https://github.com/atuinsh/atuin/issues/889

I also read [the document of zsh's HIST_IGNORE_SPACE](https://zsh.sourceforge.io/Doc/Release/Options.html), and its implementation will be more in line with my intuition:

> Remove command lines from the history list when the first character on the line is a space, or when one of the expanded aliases contains a leading space. Only normal aliases (not global or suffix aliases) have this behaviour. **Note that the command lingers in the internal history until the next command is entered before it vanishes, allowing you to briefly reuse or edit the line**. If you want to make it vanish right away without entering another command, type a space and press return.
