### ISSUE TITLE
FYI on remote build's speedFactor

### ISSUE THREAD

**Issue by ashebanow** [ryan4yin/nix-config#70]
In  [remote-building.nix](https://github.com/ryan4yin/nix-config/blob/985beb8bd47189e4b2ef5200ef5c1ab28e3812a8/modules/nixos/base/remote-building.nix#L51),  you mention that speedFactor was not used by Nix.

It is in fact used by both Hydra and nix's remote build system. For the latter, see this function:

https://github.com/NixOS/nix/blob/d83008c3a797c8e4ec1e1a97c5b1bc5e6b02c561/src/build-remote/build-remote.cc#L49

**Comment by ryan4yin** [comment]
@ashebanow Thanks for the info, it's very helpful!
