### ISSUE TITLE
Git error: nix-secrets not exist

### ISSUE THREAD

**Issue by bonnjalal** [ryan4yin/nix-config#9]
I get this errot when I try to excute : make i3 or any other command:

> nixos-rebuild switch --flake .#ai_i3 --use-remote-sudo
> building the system configuration...
> The authenticity of host 'github.com (140.82.121.4)' can't be established.
> ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
> This key is not known by any other names.
> fetching Git repository 'ssh://git@github.com/ryan4yin/nix-secrets.git'
> Host key verification failed.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> error: program 'git' failed with exit code 128
> (use '--show-trace' to show detailed location information)
> make: *** [Makefile:14: i3] Error 1
> 

And this repository  _ryan4yin/nix-secrets.git_ is not exist.

**Comment by ryan4yin** [comment]
> Note: you should NOT deploy this flake directly on your machine, it contains my hardware information and personal information which is not suitable for you. You may use this repo as a reference to build your own configuration.

`ryan4yin/nix-secrets` is a private repository, so this error is expected. see: https://github.com/ryan4yin/nix-config/tree/main/secrets

**Comment by ryan4yin** [comment]
I just updated README to make this note more visible and clear:

> Note: **you should NOT deploy this flake directly on your machine!  It will not succeed.** this flake contains my hardware configuration(such as [hardware-configuration.nix](hosts/idols/ai/hardware-configuration.nix)) which is not suitable for your hardware, and my private secrets repository [ryan4yin/nix-secrets](https://github.com/ryan4yin/nix-config/tree/main/secrets) that only I have access to. You may use this repo as a reference to build your own configuration.

**Comment by bonnjalal** [comment]
Ok, thank you very much.
