### ISSUE TITLE
Suggestion to Add Flags in Commit Messages to Highlight Updates Required in Host Machine Configuration Files

### ISSUE THREAD

**Issue by DataEraserC** [ryan4yin/nix-config#97]
When making changes to the code, I suggest considering adding a flag in the commit message to indicate which related files downstream may need modifications (e.g., host machine-related content). This practice will assist in swiftly identifying the updates needed, thus enhancing the efficiency of rolling updates.

**Comment by ryan4yin** [comment]
How about a structure like `type (< files >): message`? 
Similar commits:

- https://github.com/ryan4yin/nix-config/commit/a4d3867a73a452e3c0b8be0e5ffbf4e787e6bcfd
- https://github.com/ryan4yin/nix-config/commit/dab163bf237db2b11ed3a90e074d8a9228586a29

**Comment by DataEraserC** [comment]
> How about a structure like `type (< files >): message`? Similar commits:
> 
> * [a4d3867](https://github.com/ryan4yin/nix-config/commit/a4d3867a73a452e3c0b8be0e5ffbf4e787e6bcfd)
> * [dab163b](https://github.com/ryan4yin/nix-config/commit/dab163bf237db2b11ed3a90e074d8a9228586a29)

I think we can give this structure a try.

**Comment by ryan4yin** [comment]
@DataEraserC OK.
